ChatApp/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ChatApp.Data;
using ChatApp.Models;
using ChatApp.UtilityClassLibrary;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChatApp.Controllers
{
    [Authorize]
    public class ChatController : BaseController
    {
        //User.FindFirst(ClaimTypes.NameIdentifier).Value
        //basically this line of code get the name of the current signedin user
        private readonly AppDbContext _context;

        public ChatController(AppDbContext context) => _context = context;
        
        public IActionResult Index() => View(); 

        // public async Task<IActionResult> Index() 
        // {
        //     var chatsInDb = await _context.Chats
        //         .Include(x => x.Users)
        //         .Where(model => !model.Users
        //             .Any(y => y.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value))
        //         .ToListAsync();            
            
        //     return View(chatsInDb);
        // }                

        [HttpPost]
        public async Task<IActionResult> CreateGroup(string name)
        {
            var chat = new Models.Chat{
                Name = name,
                ChatType = ChatType.Group
            };

            chat.Users.Add(new ChatUser {
                UserId = GetUserId(),       //i don't what is happening here 
                                                                                //i think it basically take out the id of user crated when registration
                Role = UserRole.Admin
            });

            await _context.Chats.AddAsync(chat);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        [HttpPost]
        public async Task<IActionResult> CreatePrivateGroup(string userId)
        {
            var chat = new Models.Chat{                
                ChatType = ChatType.Private
            };

            chat.Users.Add(new ChatUser{
                UserId = userId,
                Role = UserRole.Member              
            });

            chat.Users.Add(new ChatUser{
                UserId = GetUserId(),
                Role = UserRole.Admin                
            });

            await _context.Chats.AddAsync(chat);

            await _context.SaveChangesAsync();
            return RedirectToAction("GetChat","Home", new { id = chat.Id });        //after calling savechanges function 
                                                                                    //_context will automatically assigned chatId to specific chat id
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetChat(int id) => 
            View("Index",await _context.Chats
            .Include(m => m.Messages)
            .FirstOrDefaultAsync(m => m.Id == id));                


        [HttpPost]
        public async Task<IActionResult> SendMessage(int Id, string message){
            var Message = new Message()
            {
                ChatId = Id,
                UserName = User.Identity.Name,
                Text = message,
                TimeStamp = DateTime.Now
            };

        await _context.Messages.AddAsync(Message);
        await _context.SaveChangesAsync();
        return RedirectToAction("GetChat", new { id = Id});
        }

        [HttpPost]
        public async Task<IActionResult> JoinGroup(int id)
        {
             var chatUser = new ChatUser {
                ChatId = id,
                UserId = GetUserId(),
                Role = UserRole.Member
            };

            await _context.ChatUsers.AddAsync(chatUser);

            await _context.SaveChangesAsync();

            return RedirectToAction("GetChat", new {id = id});
        }
    }    
}

ChatApp/ViewComponents/RoomViewComponent.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ChatApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChatApp.ViewComponents{
    public class RoomViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public RoomViewComponent(AppDbContext context) => _context = context;
        
        public async Task<IViewComponentResult> InvokeAsync(){
            var chatUser = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            
            var chatsInDb = await _context.ChatUsers
                .Include(chatuser => chatuser.Chat)
                .Where(chatuser => chatuser.UserId == chatUser)
                                    //&& chatuser.Chat.ChatType == Models.ChatType.Group)
                .Select(chatuser => chatuser.Chat)
                .ToListAsync();
            return View(chatsInDb);
        }
    }
}

ChatApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>ChatApp</title>

        <link rel="stylesheet" href="~/css/site.css" />
    </head>

    <body>
        <partial name="_Navbar" />
        <div class="main">
            @if (User.Identity.IsAuthenticated)
            {
                <vc:room></vc:room>                
            }           
            <div class ="chat" >
                @RenderBody()
            </div> 
        </div>
        <div class="modal" id="create-room-modal">
            <form asp-controller="Chat" asp-action="CreateGroup" class="modal-body">
                <button type="button" class="btn-close" onclick="closeModal()">X</button>
                <header>Create Room</header>
                <div>
                    <input name="name">
                </div>
                <footer><button class="btn-create">Create</button></footer>
            </form>
        </div>
        <script src="~/js/site.js"></script>
        @* <script src="~/js/signalr.min.js"></script>
        <script src="~/js/axios.min.js"></script> *@

        @RenderSection("Scripts",false)
    </body>  
</html>

ChatApp/Views/Shared/_Navbar.cshtml
<div class="navbar">
    <a asp-controller="Home" asp-action="Index">Home</a>
    <a asp-controller="Home" asp-action="Find">Find Some?</a>
    <a asp-controller="Home" asp-action="GetPrivateChats">Your Private Group</a>
    <a asp-controller="Home" asp-action="GetPublicChats">Public Groups</a>
</div>

    